# Generated by Django 2.1.4 on 2018-12-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyweads', '0002_auto_20181125_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
