# Generated by Django 2.1 on 2018-11-26 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181126_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 17, 13, 32, 860787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$tk1fN7RS$b6a7331b13d5aa8ca05043511536561841605e56eaf3958c57efd453eb9e5d23', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$Ow1hR0DV$550664077cebd6793cfd51877c4ddb05357bb630b49668b65758b6ae743447fd', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$mdtsrIcK$d0a3df268f491862d6dc649fef4e7e26c574ddf0d3ab265c5ae3f67facdecc94', max_length=1000),
        ),
    ]
