# Generated by Django 2.1 on 2018-11-26 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181126_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 17, 27, 8, 360282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$hU40T9W8$6a688042707c638a4df1eb089a9afd5befcb730e6239b19c25379e8a5119e8b4', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$RHmohYoG$395c44d744da5fd474ef68a304eac06c70a63dc07d6effc07c4245c8ef4e1d74', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$NdPTkZLy$03bb2f8e63e9708268f6e95f6deb47ad80ea2418ec40c9484f17708d7097e8fe', max_length=1000),
        ),
    ]
