# Generated by Django 2.1 on 2018-11-26 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181126_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 20, 0, 12, 544620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$rrrn5jhI$3da1d0f49c612a022bbed143c569c9a27d7b28290591241f6e5a5be7e44474a0', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$ouZr9o9p$d42a109d824dcfd190604ebfe503d01e7e9e270dd8e6eb4af3f3b5303d5f66d6', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$nqBL6tEI$4022c9d8f8cd8e2e00ae6fb6fc429f74c8b5ea11a4e174a4a87c23723e0101b6', max_length=1000),
        ),
    ]
