# Generated by Django 2.1 on 2018-11-26 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181126_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 22, 0, 7, 710140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$Q9Eec4vl$cc88ebfc6c33eb3203e977fdf49322e01ed07666ffb35d37025d8595e6df8dd1', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$A0yJVEn1$0ed501540b22efc4900a9b10fdc87a9da4fc75d6da8167c692a097975a5c89cc', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$0dsQAk0E$460a9b775353a021ab954c5c91ea7720a0e6497e81e31d90ab3d54ef1e338399', max_length=1000),
        ),
    ]
