# Generated by Django 2.1 on 2018-11-26 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181126_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 22, 46, 55, 71977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$K6OJmYvA$12e83c9dfa19bdd5b7cf491c1180129a6aede607d47c0911b802d3aebc08ef37', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$xUMQGcqi$2f7ebc962fed303aa78e756cccd554ed0e2168fe68a2d8a009ede79bf8f1175f', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$YmFFxXBR$cdb3d39489d0cf5c45edc57001cc7f0e6e34ff954a7d219d12140f2f1d148ad7', max_length=1000),
        ),
    ]
