# Generated by Django 2.1 on 2018-12-02 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181126_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 17, 26, 33, 428458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$DhGrfht2$830063e5bec605e48c413dd360c8b06c19ec93dee9c599a49581aa445c8223db', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$ZKr9PokS$954998682e78d55e56e430f8784ad99829b9ffaf7833a291fbcab89f069cb478', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$B15UzCMK$3abdb59165c87f5c5711968ed4006a43105fb72822eafe3a118ae676a8e19b38', max_length=1000),
        ),
    ]
