# Generated by Django 2.1 on 2018-12-02 18:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181202_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 18, 32, 18, 332393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$MaUO7mCw$bf928a2ed8ff98cdf1c31a3d7fe858bb4a813eef22a715d1a255a304f60a72ca', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$VQ6Ga92a$052266ca10b2fbf26c2de592443a5ea0749df6778ca090d8a83e5136616f22ac', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$lIaZ0vby$793990058fef65d6e748bdfe2c54ab835faf135814b705fb18f963c124843b93', max_length=1000),
        ),
    ]
