# Generated by Django 2.1 on 2018-12-02 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181202_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 20, 10, 56, 833854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 20, 10, 56, 909747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$5UywtjUg$5176b1f36a3bccda3494f4809d7fee1550c4e4c9a09ca3d0f84cef35fd2c473f', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$xKHA8rQx$95d4f7064cd9d640daeb661967e8c019b0efc535d4fc0e1d0792b072e53f2509', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$GYJ6Gxak$6a66c75cadd9d424c1277e4d71d189dec421c42a1bd6b1f13f5d66c80d0fadce', max_length=1000),
        ),
    ]
