# Generated by Django 2.1 on 2018-12-02 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181202_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 21, 12, 56, 347166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 21, 12, 56, 434850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$FqXVB3MR$81cce541c59fb9cdbd14de9c7dbfa6e2e9d4346ebdb7a033aee216d420987030', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$LV1oYCGt$6c8c8f1e166438b725886b3f9b6908a11cb2a2f7beef87ceb0298fd0a16ad781', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$XwflPt9H$d2ca3695ec67d1208db908e0b35af510144242ec33da3304d2493025a0f3e20c', max_length=1000),
        ),
    ]
