# Generated by Django 2.1 on 2018-12-02 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181202_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 21, 26, 2, 579416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 21, 26, 2, 632987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$l1NbIZrQ$ac9d110c95853fc538755a99c1be3c75eefb39963e7e165e9404677806bddc95', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$DgJP1t6B$841720b4db0116bce28a886190d453323271ce8318e01fc14633ff2a3244a247', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$t9G6C3EF$a1d7133bea2b206ef079e081b62571e553958ac16c5279d380b76d5bddbf1acf', max_length=1000),
        ),
    ]
