# Generated by Django 2.1 on 2018-12-02 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20181202_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 21, 49, 43, 590919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 21, 49, 43, 638955, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$cswAwWiw$6450e7201784af72c9daf28c9603031f4abf1971f4ab581b19a514ff65297173', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$DYyKP3EO$2d556a7cc17f2d4e427728954939674728a7c2cea2a0f81a287a6660cc8381be', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$jrb05b9j$22148eff656dcafa9d83ed702bb3806285eff9d16e0ea5a1642ddd7ef593d8ce', max_length=1000),
        ),
    ]
