# Generated by Django 2.1 on 2018-12-02 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20181202_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 22, 16, 41, 216755, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 22, 16, 41, 266866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$nXrg7De8$650619250ef4f8b136fb8bc25b988eec505d556cd3aa9ca8a59960b2fa76fd91', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$tmej8e3l$388a67427e84b5ad18da20922c1b06f6166b1797c0b193ec610e6668d27725b9', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$Djk1cBcK$fa530e53968765ead5afb3667b5674cfb1232d84693b3e9f02aef5412aa63e7f', max_length=1000),
        ),
    ]
