# Generated by Django 2.1 on 2018-12-03 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20181202_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 11, 8, 58, 799678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 11, 8, 58, 849718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$0BZ7MzP7$0a99ff784b9005b9f1d3ff041438510626fd623724b64b6b7b9fe04ac28f4d8a', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$ORS7wpFH$0b2911aac7ddb4d633a499aad5e11e0e65ef3d38aa0d6fe9e544b923562b0fe2', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$J4i65P9J$41de1c4cc78948ce008fffffa27eaf7262448aa9373a758d55736030ff56cf8b', max_length=1000),
        ),
    ]
