# Generated by Django 2.1 on 2018-12-03 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20181203_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 11, 40, 20, 142615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 11, 40, 20, 191806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$n479Nd4D$e78a0a7c1ff2ba0f77f31c7d73a38124bcc6e409f346529341987137788495c4', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$ZaaHYEFP$8da936f074079ccac0bb1fae6dfb1ac6cc6a76a222ad194e043b52af197b91d5', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$Hf7ednYp$c9d05b9ae73ddd60f4b08a506de38c026a72b77de3c279d7357972b7cad96a17', max_length=1000),
        ),
    ]
