# Generated by Django 2.1.4 on 2018-12-04 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20181204_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/static/accounts/uploads'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 14, 3, 49, 733899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 14, 3, 49, 735383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha1:1000$v83ua8lT$05cf8ee2706cb1be64e07450b9105f6cdc0d12b4', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$J45sdT40$db6432e13e9b4e677efcc1302a2851d68cac8dad', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$yjkYIfhS$89b22a562d09d8542ddebd8a756a8ff7cacd896f', max_length=1000),
        ),
    ]
