# Generated by Django 2.1.4 on 2018-12-04 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20181204_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 23, 7, 20, 53572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 23, 7, 20, 55118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha1:1000$mPtFRLQV$79f0dc72405bed965c26146904e5b0e3a49e64eb', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/accounts/uploads'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$rghPP2GV$1e189cefe458eab2ae7dddc14e97c9fc9663778c', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$bdBMqXmb$845476a77513447e16c0185e86476cdac0f430ce', max_length=1000),
        ),
    ]
