# Generated by Django 2.1.4 on 2018-12-05 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20181204_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 8, 12, 50, 622506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 5, 8, 12, 50, 623927, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha1:1000$puENH8la$9a2d967c38c6fb1d3dc0a3695cc589146bdff46c', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$8ip8VFvo$15d3a85bd8ccb9fd03f1f6d8a55ddc0f3d015354', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$lUzo4pZ2$03f9a4ac0525fbefe327694788f7da3c60e7ed9d', max_length=1000),
        ),
    ]
