# Generated by Django 2.1.4 on 2018-12-16 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20181205_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 14, 7, 51, 402893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 14, 7, 51, 406313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha1:1000$GN71RLWR$299d847c2e1173f91164902b7a538650dc4548ec', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$TcEgjIQB$9e013389edde090dd22f4c4f22f48ae9c0df6c1f', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$LJcj1x3Y$122ddea0258994981ef6518ccbaa204bbf1bbf96', max_length=1000),
        ),
    ]
