# Generated by Django 2.1.4 on 2018-12-16 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20181216_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 14, 10, 17, 141781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 14, 10, 17, 143766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha1:1000$QFZhRgEg$608e6e4fbe59139a37f7c94dc2db250362eea001', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$I8yvO9Dh$17a7a463bea672b4a9a1033e103f862806aada56', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha1:1000$UOcN3l9W$1cc832882496b93d2e56f5b4930fbf6212931fe9', max_length=1000),
        ),
    ]
