# Generated by Django 2.1.5 on 2019-01-11 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20181216_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 15, 20, 38, 477876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 15, 20, 38, 561181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$Aiu8hzKI$da4d90e233925c5d781000c7e3519b777416e8f77f9b233e4ff34d858149b5be', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$8aLpHEKa$84fb4da50a6c279d186cb0a7cc7a84c3655d1b1d71edde47c008922d5c0b5d16', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$LyjsE1HU$5657c713acdbc2e511fefe367d925922e353282f0bc2873cbc9b873770e82cb4', max_length=1000),
        ),
    ]
