# Generated by Django 2.1.5 on 2019-01-13 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20190111_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 13, 19, 31, 635167, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 13, 19, 31, 705996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$YfVhm8gd$f2912acf95c8ace692b61507ef36cfd2ea5964a038b38947dc67c2ea07cf8642', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$aZgHfC04$7603779745ce3fe629803b896fa5985704b9584560368f87d02b16b078bb438e', max_length=1000),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$tEcKZSjV$35f3602ec28cd298fc0022c02413f1904f8eba27ae2fb9c621f1f2b88ec923b6', max_length=1000),
        ),
    ]
