# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, unique=True)),
                ('firebase_path', models.CharField(max_length=250, null=True, unique=True)),
                ('file_path', models.CharField(max_length=1000, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('download_url', models.TextField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
            },
        ),
    ]
