# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, unique=True)),
                ('intro_text', models.CharField(max_length=1000, null=True)),
                ('lesson_img', models.ImageField(blank=True, null=True, upload_to='accounts/static/lessons/uploads')),
                ('img_name', models.CharField(max_length=250, null=True, unique=True)),
                ('img_path', models.CharField(max_length=1000, null=True)),
                ('img_download_url', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1)),
                ('image', models.ImageField(upload_to='accounts/static/lessons/uploads')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
            },
        ),
    ]
