# Generated by Django 2.1 on 2018-11-26 18:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20181126_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sub_topics',
            field=django_mysql.models.ListTextField(models.CharField(max_length=1000), blank=True, size=5000),
        ),
    ]
