# Generated by Django 2.1 on 2018-12-03 11:08

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_lesson_sub_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=froala_editor.fields.FroalaField(null=True),
        ),
    ]
