# Generated by Django 2.1 on 2018-12-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20181203_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
